### ISSUE TITLE
Fix the account selector UI element

### ISSUE THREAD

**Issue by mike-audi** [tiki-bar/tiki-receipt-capacitor#19]
The dropdown account picker currently does not fit the design specification (utilizes the default html form formatting).

Requires building a custom component.

**Comment by mike-audi** [comment]
![Image](https://github.com/tiki-bar/tiki-receipt-capacitor/assets/3769672/708f466b-f543-4543-a7fc-55ae4cd6edee)

**Comment by MiroBenicio** [comment]
continues in #126
